apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: frontend-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
  params:
    - name: git-source-url
      type: string
      description: source respository
      default: https://github.com/aslomoi/parksmap-web.git
    - name: image-repo
      type: string
      description: Docker image name
      default: image-registry.openshift-image-registry.svc:5000/aussie-project/parksmap-web
    - name: app-name
      type: string
      default: parksmap-web
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-source-url)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: build
      params:
        - name: IMAGE
          value: $(params.image-repo):$(tasks.clone-repository.results.commit)
        - name: TLSVERIFY
          value: "false"
      runAfter:
        - clone-repository
      taskRef:
        kind: ClusterTask
        name: s2i-java-11
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: kustomize
      taskRef:
        kind: Task
        name: kustomize-build-dyn
      params:
        - name: image-with-tag
          value: $(params.image-repo):$(tasks.clone-repository.results.commit)
        - name: existing-image-name
          value: parksmap-web/image
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: gitops
      taskRef:
        kind: Task
        name: gitops
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      params:
        - name: app-name
          value: "$(params.app-name)"
        - name: sha
          value: "$(tasks.clone-repository.results.commit)"
      runAfter:
        - kustomize
    - name: apply-manifests
      taskRef:
        name: apply-manifests
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - kustomize
