apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kustomize-build-dyn
spec:
  workspaces:
    - name: source
      description: contains the cloned git repo
  params:
    - name: existing-image-name
      type: string
    - name: image-with-tag
      type: string
      default: "image:tag"
  steps:
    - name: kustomize-build
      image: docker.io/enzobarrett/kustomize:latest
      script: |
        #!/bin/sh        
        cd source/k8s

        kustomize edit set image $(params.existing-image-name)=$(params.image-with-tag)
        kustomize build > ../manifests.yaml

        cd ..

        if [ -f manifests.yaml ]; then
          echo "manifests.yaml successfully generated"
        else
          echo "ERROR: manifests.yaml not generated"
          exit 1
        fi
