apiVersion: triggers.tekton.dev/v1alpha1 
kind: EventListener 
metadata:
  name: pipeline-trigger
spec:
  serviceAccountName: pipeline 
  triggers:
  - bindings:
    - ref: pipeline-trigger
    template: 
      name: pipeline-trigger