apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-pipeline-trigger
spec:
  host: ""
  port:
    targetPort: http-listener
  tls:
    termination: edge
  to:
    kind: Service
    name: el-pipeline-trigger